language: node_js
node_js:
  - '14'
services:
  - mongodb
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - DB_URL=mongodb://localhost:27017/reviews
    - JWT_SECRET=put_key_here
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
    - JWT_REFRESH_RESET_PASSWORD_EXPIRATION_MINUTES=30
script:
  - npm test
